apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    local.file_match "container_logs" {
      path_targets = ["/var/log/containers/*.log"]
    }

    loki.source.file "collect_logs" {
      targets    = local.file_match.container_logs.targets
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        tenant_id = "production"
        basic_auth {
          username = "alloy"
          password = "old-password-12345"
        }
      }
    }
