apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: production
  annotations:
    last-updated: "2026-06-29T00:00:00Z"
type: Opaque
stringData:
  api-token: "new-rotated-token-def456"
  db-password: "new-db-password-uvw321"
